=== alvsanand/cms/src/main/webapp/WEB-INF/xsd/mobile-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://alvsanand.appspot.com/mobile/config" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mob="http://alvsanand.appspot.com/mobile/config">
    <xs:element name="mobileConfig" type="mob:mobileConfigType"/>
    
    <xs:complexType name="mobileConfigType">
    	<xs:sequence>
    		<xs:element name="noMobilePattern" type="mob:noMobilePatternType" minOccurs="1" maxOccurs="1"/>
    		<xs:element name="defaultURL" type="mob:defaultURLType" minOccurs="1" maxOccurs="1"/>
    		<xs:element name="excludedResources" type="mob:excludedResourcesType" minOccurs="1" maxOccurs="1"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="excludedResourcesType">
    	<xs:sequence>
    		<xs:element name="urlPattern" type="mob:urlPatternType" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:simpleType name="noMobilePatternType">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="defaultURLType">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="urlPatternType">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== alvsanand/cms/src/main/webapp/WEB-INF/mobile-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<mob:mobileConfig xmlns:mob="http://alvsanand.appspot.com/mobile/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alvsanand.appspot.com/mobile/config xsd/mobile-config.xsd ">
  <mob:noMobilePattern>((?!mobile).)*</mob:noMobilePattern>
  <mob:defaultURL>/mobile</mob:defaultURL>
  
  <mob:excludedResources>
    <mob:urlPattern>/javax.faces.resource/.*</mob:urlPattern>
    <mob:urlPattern>/themes/.*</mob:urlPattern>
    <mob:urlPattern>/js/.*</mob:urlPattern>
    <mob:urlPattern>/favicon.ico</mob:urlPattern>
  </mob:excludedResources>
</mob:mobileConfig>
