=== alvsanand/cms/src/main/webapp/WEB-INF/xsd/security-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://alvsanand.appspot.com/security/config" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sec="http://alvsanand.appspot.com/security/config">
    <xs:element name="securityConfig" type="sec:securityConfigType"/>
    
    <xs:complexType name="securityConfigType">
    	<xs:sequence>
    		<xs:element name="interceptURL" type="sec:interceptURLType" minOccurs="1" maxOccurs="unbounded"/>
    		<xs:element name="defaultURL" type="sec:defaultURLType" minOccurs="1" maxOccurs="1"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="interceptURLType">
    	<xs:sequence minOccurs="1" maxOccurs="1">
    		<xs:element name="hasAllRoles" type="sec:hasAllRolesType" maxOccurs="1" minOccurs="0"/>
    		<xs:element name="hasAnyRole" type="sec:hasAnyRoleType" maxOccurs="1" minOccurs="0"/>
    		<xs:element name="hasNoRole" type="sec:hasNoRoleType" maxOccurs="1" minOccurs="0"/>
    		<xs:element name="authenticated" type="sec:authenticatedType" maxOccurs="1" minOccurs="0"/>
    	</xs:sequence>
    	<xs:attribute name="pattern" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="hasAllRolesType">
    	<xs:sequence minOccurs="1" maxOccurs="unbounded">
    		<xs:element name="role" type="sec:roleType"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="hasAnyRoleType">
    	<xs:sequence minOccurs="1" maxOccurs="unbounded">
    		<xs:element name="role" type="sec:roleType"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="hasNoRoleType">
    	<xs:sequence minOccurs="1" maxOccurs="unbounded">
    		<xs:element name="role" type="sec:roleType"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:simpleType name="roleType">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="authenticatedType">
    	<xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="defaultURLType">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== alvsanand/cms/src/main/webapp/WEB-INF/security-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sec:securityConfig xmlns:sec="http://alvsanand.appspot.com/security/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alvsanand.appspot.com/security/config xsd/security-config.xsd ">
  <sec:interceptURL pattern="/sec/admin/user/.*">
    <sec:hasAnyRole>
      <sec:role>ROLE_ADMIN</sec:role>
    </sec:hasAnyRole>
  </sec:interceptURL>
  
  <sec:interceptURL pattern="/sec/admin/eraseCache">
    <sec:hasAnyRole>
      <sec:role>ROLE_ADMIN</sec:role>
    </sec:hasAnyRole>
  </sec:interceptURL>
  
  <sec:interceptURL pattern="/sec/admin/cms/.*">
    <sec:hasAnyRole>
      <sec:role>ROLE_ADMIN</sec:role>
      <sec:role>ROLE_PUBLISHER_USER</sec:role>
    </sec:hasAnyRole>
  </sec:interceptURL>
  
  <sec:interceptURL pattern="/sec/.*">
    <sec:authenticated>true</sec:authenticated>
  </sec:interceptURL>
  
  <sec:interceptURL pattern="/.*/secured/.*">
    <sec:authenticated>true</sec:authenticated>
  </sec:interceptURL>
  
  <sec:interceptURL pattern="/login">
    <sec:authenticated>false</sec:authenticated>
  </sec:interceptURL>
  
  <sec:defaultURL>/home</sec:defaultURL>
</sec:securityConfig>
